remote_theme: just-the-docs/just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: nil
title: Filikun's Home Assistant docs
description: My Home Assistant documentation

# Enable or disable heading anchors
heading_anchors: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

kramdown:
  syntax_highlighter: rouge
