remote_theme: just-the-docs/just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
title: Filikun
description: My Home Assistant documentation
relative_permalinks: false


#baseurl: "/filikun.github.io"
#url: "https://filikun.github.io/"